baseURL = 'https://www.currentsandcontemplations.com/'
languageCode = 'en-us'
title = 'Currents and Contemplations'
theme = "PaperMod"

# Enable features
enableGitInfo = true
enableEmoji = true

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false

# Author information
[params]
  author = "Carter"
  description = "Personal blog exploring thoughts, ideas, and experiences on and off the water"
  keywords = ["blog", "fishing", "fly fishing", "colorado", "travel", "music", "personal"]
  
  # Theme-specific settings
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  
  # Homepage settings
  homeInfoParams.Title = "Currents and Contemplations"
  homeInfoParams.Content = """
Welcome to my blog! In my blog I hope to do a little justice to the memories made both on and off the water, in times of solitude and reflection, and friendship and revelry. You can expect to find musings about fishing, music, travel and other miscellaneous topics when I am inspired enough to write about them.
"""

  # Social links (update with your actual social media)
  [[params.socialIcons]]
    name = "email"
    url = "mailto:currentsandcontemplations@gmail.com"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 5
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

# Taxonomy configuration
[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

